### ISSUE TITLE
JInstaller: :Install: File does not exist .../site/attachments.php

### ISSUE THREAD

**Issue by Kimball31** [DSE-Western-Thessaloniki/attachments#1]
Got "Error installing package" package. Project pulled from github 11/17 at 12pm EST.  

JInstaller: :Install: File does not exist [ROOT][TMP]/install_655d39ec4e865/packages/install_655d39ec9d2f6/site/attachments.php
Component Update: Failed to copy site files.
Package Update: There was an error installing an extension: attachments_component.zip

**Comment by Kimball31** [comment]
If I re-install the package a second time, I get this error:

Warning
Joomla\Filesystem\File::delete: Failed deleting inaccessible file controller.php
Package Update: There was an error installing an extension: attachments_component.zip

**Comment by parapente** [comment]
I have reported a bug report to Joomla: https://github.com/joomla/joomla-cms/issues/42468

**Comment by parapente** [comment]
Should be fixed in Joomla 4.4.2
