### ISSUE TITLE
blank success message during the install process

### ISSUE THREAD

**Issue by Kimball31** [DSE-Western-Thessaloniki/attachments#2]
https://github.com/DSE-West-Thessaloniki/attachments/blob/4a976c16c32e665c02fd65c948b1f78c86952805/attachments_component/install.attachments.php#L173C3-L173C3

This line produces a blank success message during the install process. Should probable be removed.  
`$app->enqueueMessage('< br / >', 'message');`

**Comment by parapente** [comment]
Fixed in #3
